services:
  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: go_notify_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: go_notify_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data # This refers to the top-level volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d go_notify_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis
  redis:
    image: redis:7-alpine
    container_name: go_notify_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data # This refers to the top-level volume
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
  redis_data: