// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (uuid.UUID, error)
	GetAllSentMessages(ctx context.Context, arg GetAllSentMessagesParams) ([]GetAllSentMessagesRow, error)
	GetPendingMessages(ctx context.Context, limit int32) ([]GetPendingMessagesRow, error)
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
}

var _ Querier = (*Queries)(nil)
